### ISSUE TITLE
[Symfony\Component\Debug\Exception\FatalThrowableError]   Call to undefined method Closure::__set_state()

### ISSUE THREAD

**Issue by jmichaelterenin** [exodusanto/Laravel-Admin#12]
Local Environment PHP Version: 5.6.4
Production Environment PHP Version: 7.0.19

I experienced this in my local environment for the permission config value, since it's a function, and function closures are no longer acceptable in Laravel 5.4. The solution was to create a Custom Helper. I did not experience any issues with the individual Model Config files, but when I moved the code up to production, I found that I was getting this error for all the functions inside the Model Config files. An example:

```
'output' => function($value) {
	    		return ( floor($value*100) == $value*100 ? number_format($value*100, 0) : number_format($value*100, 2, '.', '') ).'%';
}	

```
The work to create Helpers for these Config files will be significant, as I am using the Administrator for 2 different menus, for 2 different roles, and the ability to create/update/delete changes frequently, depending on the model.

Is there a work around I am missing here, or will I have to create Custom Helpers for the individual model config files as well?

**Comment by exodusanto** [comment]
Hi @jmichaelterenin, do you used ```php artisan config:cache``` ?

**Comment by jmichaelterenin** [comment]
Hi @exodusanto, that throws the error as well.

**Comment by exodusanto** [comment]
Can you check if ```bootstrap/cache/config.php``` exists? And delete it

**Comment by jmichaelterenin** [comment]
It currently does not exist and I've deleted it in the past in hopes of resolving this.

**Comment by jmichaelterenin** [comment]
I think the key issue here is that is works in my local environment. What other environmental issues besides PHP version is necessary to worry about it in this case, do you think?

**Comment by exodusanto** [comment]
I think that you can try to change PHP version, but in the meantime also can you share the log

**Comment by jmichaelterenin** [comment]
The ridiculously stupid problem with changing the PHP version, is that the only version my hosting company has below 7.0 is 5.6.3, which is one notch below the requirement for Laravel 5.4 (PHP v 5.6.4).

```
[2017-05-31 17:24:28] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Closure::__set_state() in /home/tikitour/project/tikitour/bootstrap/cache/config.php:323
Stack trace:
#0 /home/tikitour/project/tikitour/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php(27): require()
#1 /home/tikitour/project/tikitour/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(208): Illuminate\Foundation\Bootstrap\LoadConfiguration->bootstrap(Object(Illuminate\Foundation\Application))
#2 /home/tikitour/project/tikitour/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(160): Illuminate\Foundation\Application->bootstrapWith(Array)
#3 /home/tikitour/project/tikitour/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->bootstrap()
#4 /home/tikitour/project/tikitour/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#5 /home/tikitour/project/tikitour/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#6 {main}  
[2017-05-31 11:25:12] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Illuminate\Foundation\Application::share() in /home/tikitour/project/tikitour/vendor/frozennode/administrator/src/Frozennode/Administrator/AdministratorServiceProvider.php:62
Stack trace:
#0 /home/tikitour/project/tikitour/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(568): Frozennode\Administrator\AdministratorServiceProvider->register()
#1 /home/tikitour/project/tikitour/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(74): Illuminate\Foundation\Application->register(Object(Frozennode\Administrator\AdministratorServiceProvider))
#2 /home/tikitour/project/tikitour/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(543): Illuminate\Foundation\ProviderRepository->load(Array)
#3 /home/tikitour/project/tikitour/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\Foundation\Application->registerConfiguredProviders()
#4 /home/tikitour/project/tikitour/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(208): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
#5 /home/tikitour/project/tikitour/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(160): Illuminate\Foundation\Application->bootstrapWith(Array)
#6 /home/tikitour/project/tikitour/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->bootstrap()
#7 /home/tikitour/project/tikitour/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#8 /home/tikitour/project/tikitour/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#9 {main}  
```

**Comment by exodusanto** [comment]
It's that file 💀 ```/home/tikitour/project/tikitour/bootstrap/cache/config.php```, you have to remove it.

Laravel know this [issue](https://github.com/laravel/framework/issues/9625) and won't fix it...

**Comment by jmichaelterenin** [comment]
@exodusanto , I promise you, it's not there, I'm sorry. I wish that was the solution. 
I have to leave now, will be back online in a few hours, thanks for your attention to this thus far, it's greatly appreciated. I'm pulling my hair out ...

**Comment by Bulmer** [comment]
Just a thought ( and it may be unrelated), but I had a Precision Error
surface , in the paypal/omnipay package and from memory I fixed it by
passing the var through number_format() one last time before posting the
data. The problem only occurred in php7.0/7.1.

**Comment by jmichaelterenin** [comment]
Looking back, I don't know why I shared that log with you where there was a config file, but here's the more recent log:

```
[2017-06-01 17:19:51] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Foundation\Application::share()' in /home/tikitour/project/tikitour/vendor/frozennode/administrator/src/Frozennode/Administrator/AdministratorServiceProvider.php:62
Stack trace:
#0 {main}  
```
I'm just going to start working more on this now, had some other work to attend to last night, and had a root canal this morning.

**Comment by jmichaelterenin** [comment]
It's pretty obvious you've written your package to overwrite the AdministratorServiceProvider that the Frozennode package provides, to use the singleton. Attached is the bootstrap/cache directory contents. 
Is there anything else that you can think of that needs to be cleared? What you see me doing in the attachment is the back part of removing your package and performing a composer update.

![cache_dir](https://cloud.githubusercontent.com/assets/8676120/26710371/2b61d78a-470e-11e7-80aa-7e101917c6d7.png)

**Comment by jmichaelterenin** [comment]
I ended up figuring out that I couldn't use the env (or config) helper to grab the domain value for administrator.php, which doesn't make any sense to me, considering it's using the config_path helper for the model/settings config path. But specifically, using env would require that I have a config cache? Because it's in the .env file, yet was coming up NULL when it came time to get the administrator config options.

**Comment by kasra-appscore** [comment]
I resolved it by removing this: bootstrap/cache/config.php
