### ISSUE TITLE
Fix needed for Boolean filter when used in tandem with another filter

### ISSUE THREAD

**Issue by jmichaelterenin** [exodusanto/Laravel-Admin#15]
Hi Antonio,

There's a bug in Boolean Filters where the $this->validator->arrayGet method returns a value with the gettype() of 'NULL', when it's normally a 'string'. I am only seeing this issue when you have another filter in use (ie datetime, string, relationship). It causes the query to include the boolean filter when it's not being used, providing erroneous results.

My solution is in Frozennode/Administrator/Fields/Boolean, and I check to make sure the gettype is NOT 'NULL', as it gets switched to an 'integer' within setFilter. The 2 changes are shown below (end of Boolean.php), look for **gettype($this->userOptions['value']) != 'NULL' &&** :

```
        /**
	 * Sets the filter options for this item
	 *
	 * @param array		$filter
	 *
	 * @return void
	 */
	public function setFilter($filter)
	{
		parent::setFilter($filter);

		$this->userOptions['value'] = $this->validator->arrayGet($filter, 'value', '');
		
		//if it isn't null, we have to check the 'true'/'false' string
		if (gettype($this->userOptions['value']) != 'NULL' && $this->userOptions['value'] !== '')
		{			
			$this->userOptions['value'] = $this->userOptions['value'] === 'false' || !$this->userOptions['value'] ? 0 : 1;
		}
	}

	/**
	 * Filters a query object
	 *
	 * @param \Illuminate\Database\Query\Builder	$query
	 * @param array									$selects
	 *
	 * @return void
	 */
	public function filterQuery(QueryBuilder &$query, &$selects = null)
	{
		//if the field isn't empty
		if (gettype($this->userOptions['value']) != 'NULL' && $this->getOption('value') !== '')
		{
			$query->where($this->config->getDataModel()->getTable().'.'.$this->getOption('field_name'), '=', $this->getOption('value'));
		}
	}

```
Let me know if there's anything else you need.

**Comment by exodusanto** [comment]
@jmichaelterenin ok, can you open a PR?

**Comment by jmichaelterenin** [comment]
Hi Antonio,
The 'Create Pull Request' button is disabled for me (I'm logged in), and I've never done this before. Not sure what to do in this scenario?

It's also very possible the fix should be in the validator, I didn't track the issue to that level.

**Comment by exodusanto** [comment]
@jmichaelterenin I updated, can you test it now?

**Comment by jmichaelterenin** [comment]
The button is still disabled, I've attached a screen shot.

![pullrequest](https://user-images.githubusercontent.com/8676120/28042972-90f861f6-6584-11e7-86b1-25ad1c866086.png)

**Comment by exodusanto** [comment]
Yes, you have to create a fork before
![image](https://user-images.githubusercontent.com/13484843/28059110-5c4f5758-6623-11e7-97e9-ce5d579e418b.png)

But I already update with the fix, now you can update with composer and test it.

**Comment by jmichaelterenin** [comment]
composer update did not download the latest version for me.  I even tried removing the composer.lock file, and performing: `composer install exodusanto/administrator`. Please advise, thanks

**Comment by exodusanto** [comment]
Can you try again?

**Comment by jmichaelterenin** [comment]
```
composer update exodusanto/administrator
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package egeloen/http-adapter is abandoned, you should avoid using it. Use php-http/httplug instead.
Writing lock file
```

**Comment by exodusanto** [comment]
Did you set ```dev-master``` ?

```
"exodusanto/administrator": " dev-master"
```

**Comment by jmichaelterenin** [comment]
No sir, it updates now with the latest, and I tested it, works. 
I did mention to you: I've never done this before. : )
