### ISSUE TITLE
Http Error: alert when trying to upload images

### ISSUE THREAD

**Issue by jmichaelterenin** [exodusanto/Laravel-Admin#24]
Laravel 5.7.25
Laravel-Admin v5.7.0
PHP v7.1.8

This was working for me at one time, but I recently noticed it's now broken. I can't get any image to upload. I made sure I had the latest version of the package.
I'm attempting the basic upload (no complicated options):

```
'header_img' => array(
		'type' => 'image',
        	'title' => 'Header Image',
        	'location' => public_path() . '/uploads/buttons/headers/',
        	'naming' => 'random',
        	'length' => 20,	
),
```
The directory exists, and as mentioned before, this was working for me.
Anyone having this issue? I've tried placing the original image to upload in c:/tmp, to eliminate any strange upload paths that might cause an issue.

Please reply to help me, and I thank you in advance.

**Comment by exodusanto** [comment]
Hi @jmichaelterenin, I try to recreate your use-case:

```php
<?php

return [
    /**
     * Model title
     *
     * @type string
     */
    'title' => 'Images',
    /**
    * The singular name of your model
    *
    * @type string
    */
    'single' => 'image',
    /**
     * The class name of the Eloquent model that this config represents
     *
     * @type string
     */
    'model' => 'App\Image',/**
    * The columns array
    *
    * @type array
    */
    'columns' => array(
        'id' => array(
            'title' => 'ID'
        ),
        'name' => array(
            'title' => 'Image',
            'output' => '<img src="/uploads/buttons/headers/(:value)" height="100" />',
        ),
    ),
    /**
    * The edit fields array
    *
    * @type array
    */
    'edit_fields' => array(
        'name' => array(
            'type' => 'image',
            'title' => 'Image',
            'location' => public_path() . '/uploads/buttons/headers/',
            'naming' => 'random',
            'length' => 20,
        )
    )
];
```

![image](https://user-images.githubusercontent.com/13484843/54265219-1823cb80-4575-11e9-98ea-f652f027d5da.png)

And the image url is:
![image](https://user-images.githubusercontent.com/13484843/54265237-21149d00-4575-11e9-9a18-a722bd106ad4.png)

Can you provide more information about the http error? It is perhaps a environment problem

**Comment by jmichaelterenin** [comment]
Thank you for your swift reply. I'm sorry, I should've realized that it's some problem on my end when I saw the small number of issues listed on your version of the package (and all closed out), indicating that you are on top of things.

Any advice for what I may be missing here with regard to the environment? It has me stuck, as it's happening both on production (Unix) and locally (Windows PC).

Regardless of whether you think of anything, this is closed. Thanks again.

**Comment by jmichaelterenin** [comment]
Maybe some direction on the location of the code (javascript? PHP?) that is performing the upload when I get this error? Maybe putting some debug in there will alert me to my problem?
