### ISSUE TITLE
throw new LogicException('Your configuration files are not serializable.', 0, $e);

### ISSUE THREAD

**Issue by tiznull** [exodusanto/Laravel-Admin#25]
Configuration cache cleared!

   LogicException  : Your configuration files are not serializable.

  at master/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/ConfigCacheCommand.php:68
    64|             require $configPath;
    65|         } catch (Throwable $e) {
    66|             $this->files->delete($configPath);
    67|
  > 68|             throw new LogicException('Your configuration files are not serializable.', 0, $e);
    69|         }
    70|
    71|         $this->info('Configuration cached successfully!');
    72|     }

  Exception trace:

  1   Error::("Call to undefined method Closure::__set_state()")
      master/laravel/bootstrap/cache/config.php:650

  2   require()
      master/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/ConfigCacheCommand.php:64

Every thread says delete this file "master/laravel/bootstrap/cache/config.php", but this file does not even exist.  How can a file throw an error that is not even there?

**Comment by jmichaelterenin** [comment]
Try physically removing the vendor directory, clear your cache and try again. It works, I've had this error occur in the past, and something to the effect of what I said has been the solution.

**Comment by tiznull** [comment]
Thanks for the reply. Unfortunately, still the same error. I understand that the issue is related to a badly coded file, it just doesn't tell me which file.  The error is related to master/laravel/bootstrap/cache/config.php:650, but that file does not exist at all.
