### ISSUE TITLE
BadMethodCallException getOwnerKey() and getForeignKey() in Fields/Relationships/BelongsTo.php and Columns/Relationships/BelongsTo.php

### ISSUE THREAD

**Issue by jellesimons** [exodusanto/Laravel-Admin#30]
Laravel version: 5.8.35
PHP version: 7.2.22
exodusanto/administrator version: 5.8.0

There is a problem with two method names inherited from Illuminate/Database/Eloquent/Relations/Relation.php

Method getOwnerKey() is named getOwnerKeyName() and method getForeignKey() is named getForeignKeyName().

In file Fields/Relationships/BelongsTo.php:

line 32: $options['foreign_key'] = $relationship->getForeignKeyName();

In File Columns/Relationships/BelongsTo.php:

- line 115: ' = ' . $last_alias . '.' . $relationship->getForeignKeyName();

- line 126: $where = $this->tablePrefix . $first_model->getTable() . '.' . $first_relationship->getForeignKeyName() .

- line 144: $fk = $nested['models'][0]->{$nested['pieces'][0]}()->getForeignKeyName();

-line 114: ' ON ' . $alias . '.' . $relationship->getOwnerKeyName() .

- line 128: $field_table . '.' . $first_relationship->getOwnerKeyName();

**Comment by jmichaelterenin** [comment]
I just upgraded to:
PHP 7.2.24
Laravel version 5.8.35
exodusanto/administrator version: 5.8.0

and pages in Admin that were working for years are now broken (same error). Please respond when you have a chance.

**Comment by exodusanto** [comment]
Can someone share an example of model configuration?

**Comment by jmichaelterenin** [comment]
Hi exodusanto,
Thank you for replying. It seems like you're not experiencing it at all? It's actually broken every page I've created. And this didn't occur when I upgraded to 5.8, it's when I upgraded to PHP 7.2.24.

I'll provide a model configuration shortly.

**Comment by exodusanto** [comment]
Thank you.
I'm recently push on `develop` branch the update of methods name. 
Can you try the fix? In your `composer.json` add the [VCS ](https://getcomposer.org/doc/05-repositories.md#vcs) section and update the package version with `dev-develop`

**Comment by jmichaelterenin** [comment]
review.php

<?php

namespace App;

/*
 * Created on Oct 1, 2014
 *
 * To change the template for this generated file go to
 * Window - Preferences - PHPeclipse - PHP - Code Templates
 */

require_once('uploadable.class.php');

class Review extends Uploadable
{

    /**
     * Ardent validation rules
     */
    public static $rules = [
      'reservation_id' => 'required',
      'title' => 'required',
      'score' => 'required|integer|between:1,10',
    ];

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'reviews';

    // MASS ASSIGNMENT -------------------------------------------------------
    // define which attributes are mass assignable (for security)
    // we only want these 2 attributes able to be filled

    protected $fillable = ['reservation_id', 'title', 'blurb', 'score', 'reviewed'];

    public static function boot()
    {
        parent::boot();

        static::updating(function ($review) {
            // Set reviewed_on timestamp if it's being changed to 'reviewed'
            if ($review->reviewed && $review->isDirty(['reviewed'])) {
                $review->reviewed_on = date('Y-m-d H:i:s');
            }
        });
    }
    
    public function reservation()
    {
        return $this->belongsTo('App\reservation');
    }
}
`
and Laravel Administrator model configuration:

`<?php
/*
 * Created on Oct 1, 2014
 *
 * To change the template for this generated file go to
 * Window - Preferences - PHPeclipse - PHP - Code Templates
 */

 return array(

	 /**
	 * Model title
	 *
	 * @type string
	 */
	'title' => 'Reviews',

	/**
	 * The singular name of your model
	 *
	 * @type string
	 */
	'single' => 'Hotel Review',

	/**
	 * The class name of the Eloquent model that this config represents
	 *
	 * @type string
	 */
	'model' => '\App\review',

	/**
	 * The columns array
	 *
	 * @type array
	 */
	'columns' => array(
		'facility' => array(
			'title' => 'Facility',
			'relationship' => 'reservation.facility.entity',
			'select' => '(:table).name',
		),
		'user' => array(
			'title' => 'Reviewer',
			'relationship' => 'reservation.user',
			'select' => '(:table).email',
		),
		'title' => array(
			'title' => 'Title',
		),
		'score' => array(
			'title' => 'Score',			
		),
		'submitted_on' => array(
			'title' => 'Review Timestamp',
		),
		'reviewed' => array(
			'title' => 'Reviewed?',
			'select' => "IF((:table).reviewed, 'yes', 'no')",	
		),
		'reviewed_on' => array(
			'title' => 'Reviewed on',				
		),		
	),
	'edit_fields' => array(
		'reservation' => array(
			'title' => 'Reservation',
			'type' => 'relationship',
			'name_field' => 'title',	
		),	
		'title' => array(
			'title' => 'Title',
			'limit' => 40,			
		),
		'blurb' => array(
			'title' => 'Review',
			'type' => 'textarea',
			'limit' => 400,				
		),
		'score' => array(
			'title' => 'Score (1-10)',
			'type' => 'number',					
		),	
		'reviewed' => array(
			'title' => 'Reviewed?',
			'type' => 'bool',
		),	
	),


	'filters' => array(
		'reviewed' => array(
			'title' => 'Reviewed?',
			'type' => 'bool',	
		),	
	),

 	/**
 	  * The query filter option lets you modify the query parameters before Administrator begins to construct the query. For example, if you want
 	  * to have one page show only deleted items and another page show all of the items that aren't deleted, you can use the query filter to do
 	  * that.
 	  *
 	  * @type closure
 	  */
 	'query_filter'=> function($query)
 	{
 		 if (!Auth::user()->hasRole('Admin') &&  Auth::user()->hasRole('Provider'))
 		 {
 		 	// $user = Auth::user();
 		 	// $query->join('services', 'service_locations.service_id', '=', 'services.id')
 		 	// ->join('providers', 'services.provider_id', '=', 'providers.id')
 		 	// ->where('providers.admin_id', '=', $user->id);
 		 }
 	},

	'permission'=> function()
	{
		$admin_exists = \App\Roleuser::where('role_id', '=', 1)->first();
		if ( !is_null($admin_exists) ) {
	    	return (Auth::check() && (Auth::user()->hasRole('Admin') || Auth::user()->hasRole('Provider')));
		} else {
			return true;
		}
	},

	'action_permissions'=> array(
		'create' => function($model) {
			return true;
		},
		'delete' => function($model) {
			return true;
		},
		'update' => function($model) {
			return true;
		},
	),

	'sort' => array(
	    'field' => 'created_at',
	    'direction' => 'desc',
	),


 )



?>
`
I tried to find a simple/basic one. It's broken everywhere.

**Comment by jmichaelterenin** [comment]
I must be doing something wrong with your instructions, namely because I've never done this before:

`"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/exodusanto/Laravel-Admin"
        }
    ], `

`"require": {
        "php": "^7.1.3",
        "anhskohbo/no-captcha": "^3.0",
        "chriskonnertz/open-graph": "^1.0",
        "cmgmyr/messenger": "^2.16",
        "cviebrock/eloquent-sluggable": "^4.7",
        "doctrine/dbal": "^2.8",
        "egeloen/http-adapter": "^1.0",
        "eilander/gateway": "^5.6",
        "exodusanto/administrator": "dev-develop",`

What am I doing wrong?

**Comment by jmichaelterenin** [comment]
Btw, I have updated the php version to "^7.2.24"
Awaiting your reply, not getting your develop version.

**Comment by jmichaelterenin** [comment]
I'm including the error log output for your reference:

`[2019-11-06 08:09:28] local.ERROR: Call to undefined method Illuminate\Database\Eloquent\Relations\BelongsTo::getForeignKey() {"userId":1,"exception":"[object] (BadMethodCallException(code: 0): Call to undefined method Illuminate\\Database\\Eloquent\\Relations\\BelongsTo::getForeignKey() at C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Traits\\ForwardsCalls.php:50)
[stacktrace]
#0 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Traits\\ForwardsCalls.php(36): Illuminate\\Database\\Eloquent\\Relations\\Relation::throwBadMethodCallException('getForeignKey')
#1 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Relations\\Relation.php(386): Illuminate\\Database\\Eloquent\\Relations\\Relation->forwardCallTo(Object(Illuminate\\Database\\Eloquent\\Builder), 'getForeignKey', Array)
#2 C:\\xampp\\htdocs\\explore\\vendor\\exodusanto\\administrator\\src\\Frozennode\\Administrator\\Fields\\Relationships\\BelongsTo.php(32): Illuminate\\Database\\Eloquent\\Relations\\Relation->__call('getForeignKey', Array)
#3 C:\\xampp\\htdocs\\explore\\vendor\\exodusanto\\administrator\\src\\Frozennode\\Administrator\\Fields\\Field.php(246): Frozennode\\Administrator\\Fields\\Relationships\\BelongsTo->build()
#4 C:\\xampp\\htdocs\\explore\\vendor\\exodusanto\\administrator\\src\\Frozennode\\Administrator\\Fields\\Field.php(263): Frozennode\\Administrator\\Fields\\Field->getOptions()
#5 C:\\xampp\\htdocs\\explore\\vendor\\exodusanto\\administrator\\src\\Frozennode\\Administrator\\Fields\\Factory.php(409): Frozennode\\Administrator\\Fields\\Field->getOption('field_name')
#6 C:\\xampp\\htdocs\\explore\\vendor\\exodusanto\\administrator\\src\\viewComposers.php(21): Frozennode\\Administrator\\Fields\\Factory->getEditFields()
#7 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(347): Frozennode\\Administrator\\AdministratorServiceProvider->{closure}(Object(Illuminate\\View\\View))
#8 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(196): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('composing: admi...', Array)
#9 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Concerns\\ManagesEvents.php(179): Illuminate\\Events\\Dispatcher->dispatch('composing: admi...', Array)
#10 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(123): Illuminate\\View\\Factory->callComposer(Object(Illuminate\\View\\View))
#11 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(90): Illuminate\\View\\View->renderContents()
#12 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(156): Illuminate\\View\\View->render()
#13 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(142): Illuminate\\View\\View->gatherData()
#14 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(125): Illuminate\\View\\View->getContents()
#15 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(90): Illuminate\\View\\View->renderContents()
#16 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Response.php(42): Illuminate\\View\\View->render()
#17 C:\\xampp\\htdocs\\explore\\vendor\\symfony\\http-foundation\\Response.php(202): Illuminate\\Http\\Response->setContent(Object(Illuminate\\View\\View))
#18 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(748): Symfony\\Component\\HttpFoundation\\Response->__construct(Object(Illuminate\\View\\View))
#19 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(720): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Illuminate\\View\\View))
#20 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(680): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Illuminate\\View\\View))
#21 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 C:\\xampp\\htdocs\\explore\\vendor\\exodusanto\\administrator\\src\\Frozennode\\Administrator\\Http\\Middleware\\PostValidate.php(48): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Frozennode\\Administrator\\Http\\Middleware\\PostValidate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 C:\\xampp\\htdocs\\explore\\vendor\\exodusanto\\administrator\\src\\Frozennode\\Administrator\\Http\\Middleware\\ValidateModel.php(25): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Frozennode\\Administrator\\Http\\Middleware\\ValidateModel->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 C:\\xampp\\htdocs\\explore\\vendor\\exodusanto\\administrator\\src\\Frozennode\\Administrator\\Http\\Middleware\\ValidateAdmin.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Frozennode\\Administrator\\Http\\Middleware\\ValidateAdmin->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 C:\\xampp\\htdocs\\explore\\app\\Http\\Middleware\\VerifyCsrfToken.php(74): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): App\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#50 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#51 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#52 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#53 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#54 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#55 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#56 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#57 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#60 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#63 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 C:\\xampp\\htdocs\\explore\\app\\Http\\Middleware\\CheckForMaintenanceMode.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#66 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): App\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#69 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#70 C:\\xampp\\htdocs\\explore\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#71 C:\\xampp\\htdocs\\explore\\public\\index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#72 {main}
"} 
`

**Comment by jmichaelterenin** [comment]
Yes, that version is working as expected. Thank you for the fix. Let me know when it's committed.

**Comment by exodusanto** [comment]
Fixed in version `5.8.1`
