### ISSUE TITLE
Modifying Laravl-Admin from 5.8 -> 7.x of Laravel? -- Is this possible?

### ISSUE THREAD

**Issue by numinds** [exodusanto/Laravel-Admin#32]
jan@frozennode.com, info@antoniodalsie.com, t

Hi  Jan/Antonio

You don't know me. We've never talked. I'm hoping one or more of you, might be willing to help me figure out if your app/package ("frozennode/administrator") is suitable for an app/project within Github.  

I'm looking to possibly port an older Github/Laravel App. The app --https://github.com/jonstavis/prelaunchr-laravel, apparantly uses the v5.8 version of Laravel. Given that I'm running v7 of Laravel, I'm trying to see what would be required to mod the pelaunchr app to get it to run for Laravel v7.

I'm at the point where I'm examining the 
 		"frozennode/administrator": "5.*", <<< 
which runs at v5. 

Unfortunately this app/package is no longer supported. Searching Github/Packagelist gets me to the >>>Lavael-Admin <<<  or https://github.com/exodusanto/Laravel-Admin.

Is this app/package a replacement for the "frozennode/administrator" app/package?

If it is a "replacement", can it be modified to work with the current version v7 of Laravel instead of the v5.8 Laravel?

Look forward to talking to you about what I should do for this situation!

Thanks

-bruce

**Comment by exodusanto** [comment]
Hi @numinds 

This package now support Laravel 7.x, you can update `composer.json`

```json
"exodusanto/administrator": "7.*"
```

**Comment by jmichaelterenin** [comment]
@exodusanto You've done some yeoman's work upgrading administrator all the way to 8. Thank you fine sir!
Just an FYI, I was going to stop at 7 (from 5.8), but I was getting the "undefined [itemconfig]" error that was reported by someone with the Laravel 8 upgrade, strangely enough ...
