### ISSUE TITLE
Compatible with Laravel 8?

### ISSUE THREAD

**Issue by Bulmer** [exodusanto/Laravel-Admin#36]
I'm looking at upgrading my Laravel app soon and need to know if this great admin will be updated to run on Laravel 8 or if there are any problems running it on that version?

**Comment by exodusanto** [comment]
Hi, I will try to run some tests and update the vendors.

**Comment by Bulmer** [comment]
I've got my app running Laravel 8 now, without administrator. Is there a way I can install it and test it out?

**Comment by exodusanto** [comment]
I pushed a wip branch feature/laravel-8, you can test it with `dev-feature/laravel-8` version for composer

**Comment by Bulmer** [comment]
Ok, got it installed and first error (on any administrator routes):
ReflectionFunction::__construct() expects parameter 1 to be string, array given.
vendor/laravel/framework/src/Illuminate/Routing/RouteSignatureParameters.php:27

**Comment by Bulmer** [comment]
I think the issue is that the routes file needs rewriting to the L8 style, as explained here:
https://mangyfoil.com/typeerror-reflectionfunction__construct-expects-parameter-1-to-be-string-array-given/
I've tried rewriting the base route like this: 
Route::get('/',[AdminController::class,'dashboard'])->name('dashboard');
But i'm now getting a "Target class [itemconfig] does not exist" error.

**Comment by exodusanto** [comment]
These days I’ve been working on phpunit upgrade, tests now are ok. 
If you want you can try now with the same branch

**Comment by Bulmer** [comment]
Which branch is that?

**Comment by exodusanto** [comment]
`dev-feature/laravel-8`

**Comment by Bulmer** [comment]
Ok, updated and still getting:
Illuminate\Contracts\Container\BindingResolutionException
Target class [itemconfig] does not exist.

**Comment by Bulmer** [comment]
Are you getting the "Target class [itemconfig] does not exist." error at all?

**Comment by exodusanto** [comment]
I made some fixes, now seems to work.

**Comment by Bulmer** [comment]
Yes, it seems ok here too. I'll post here if I find any problems.
As Laravel 8 now has a dedicated directory for Models, the setting for the various administrator model configs needs adjusting from 'model' => 'App\User', to 'model' => 'App\Models\User',

**Comment by exodusanto** [comment]
You can use this syntax `models => User::class`, and import the namespace

**Comment by Bulmer** [comment]
Tested in local dev setup for a few months and just went live. Also using php8.0-fpm. Im getting this message:
`Got error 'PHP message: PHP Deprecated:  Required parameter $fields follows optional parameter $id in /website/vendor/exodusanto/administrator/src/Frozennode/Administrator/Config/Model/Config.php on line 114PHP message: PHP Deprecated:  Required parameter $columns follows optional parameter $id in /website/vendor/exodusanto/administrator/src/Frozennode/Administrator/Config/Model/Config.php on line 114'`

**Comment by Bulmer** [comment]
I only saw this once, so i'd say it can be disregarded. I'll keep an eye out and post back here if any ongoing problems arise.

**Comment by exodusanto** [comment]
Hi @Bulmer, this is a php 8 problem.

There is a huge refactor for the php8 support due the new rule for optional parameters order.

If you want u can open a new issue
