### ISSUE TITLE
PHP8.0 error

### ISSUE THREAD

**Issue by Bulmer** [exodusanto/Laravel-Admin#38]
I've tested Laravel-Admin with Laravel 8 / PHP8 in local dev setup for a few months and just went live. 
Im getting this message deprecated message:
Got error 'PHP message: PHP Deprecated: Required parameter $fields follows optional parameter $id in /website/vendor/exodusanto/administrator/src/Frozennode/Administrator/Config/Model/Config.php on line 114 PHP message: PHP Deprecated: Required parameter $columns follows optional parameter $id in /website/vendor/exodusanto/administrator/src/Frozennode/Administrator/Config/Model/Config.php on line 114'

**Comment by Bulmer** [comment]
I see you've made a few changes to Config.php. Would you like me to test them on my dev setup? If so, could you explain how I should go about it? Running composer update comes up with version errors for "dev-feature/laravel-8"

**Comment by exodusanto** [comment]
Hi @Bulmer you can test it using the new versione `8.1.0`.
Thanks

**Comment by Bulmer** [comment]
Thanks for that. So far, so good! I'll let you know if I come across anything else.
