### ISSUE TITLE
Laravel 8: Class 'Illuminate\Support\Facades\Input' not found

### ISSUE THREAD

**Issue by catweasel** [exodusanto/Laravel-Admin#41]
Trying to upload a file or image results in Class 'Illuminate\Support\Facades\Input' not found error in vendor/exodusanto/administrator/src/Frozennode/Administrator/Includes/Multup.php

Illuminate\Support\Facades\Input was removed in Laravel 6, should instead be using the Request facade.

I am using version 8.0.0

**Comment by Bulmer** [comment]
You should use the Request facade, as the warning says @catweasel . You can't use Input:: anymore in Laravel 8

**Comment by catweasel** [comment]
Yes @Bulmer that's my point, this package should be using the Request facade so I've opened this issue asking it be changed from Input to Request.
There was no warning to use the Request facade, that's my comment.

**Comment by exodusanto** [comment]
Hi @catweasel
I create a new branch with the updated code`bugfix/update-input-facade-with-request`, can u test it?

Note: u can follow the [composer docs](https://getcomposer.org/doc/05-repositories.md) to configure your local composer configuration

**Comment by catweasel** [comment]
@exodusanto I've updated my local env with "exodusanto/administrator": "dev-bugfix/update-input-facade-with-request" and this has fixed the issue. Thank you very much for such a quick turn around

**Comment by exodusanto** [comment]
This fix is available in `8.1.1`
