### ISSUE TITLE
just fresh install it and got an error

### ISSUE THREAD

**Issue by sweggggg** [exodusanto/Laravel-Admin#5]
went in and typed /admin at url and got this error

InvalidArgumentException in Factory.php line 106:
There are problems with your administrator.php config: The model config path option must be a valid directory. The settings config path option must be a valid directory. The menu field is required.

**Comment by exodusanto** [comment]
Hi @sweggggg,

To fix those errors you can find the solution here

**Model config path**: https://github.com/exodusanto/Laravel-Admin/blob/master/docs/configuration.md#model-config-path
**Settings config path**: https://github.com/exodusanto/Laravel-Admin/blob/master/docs/configuration.md#settings-config-path
**Menu**: https://github.com/exodusanto/Laravel-Admin/blob/master/docs/configuration.md#menu

**Comment by sweggggg** [comment]
Done exactly what it says, still got an errors

![capture](https://cloud.githubusercontent.com/assets/26056229/23695895/502aa8ba-041c-11e7-8e00-c2710b6c2bad.PNG)

**Comment by Bulmer** [comment]
I seem to remember I had a problem using the standard entry and used these:
	'model_config_path' => config_path('administrator'),
	'settings_config_path' => config_path('administrator/settings'),

**Comment by exodusanto** [comment]
Yes, i will update the docs:

```
/**
 * The path to your model config directory
 *
 * @type string
 */
'model_config_path' => config_path('administrator'),

/**
 * The path to your settings config directory
 *
 * @type string
 */
'settings_config_path' => config_path('administrator/settings'),
```
