### ISSUE TITLE
Fatal error: Class 'DB' not found in C:\xampp\htdocs\laravel5\config\administrator\

### ISSUE THREAD

**Issue by jmichaelterenin** [exodusanto/Laravel-Admin#9]
Hi there,
I'm doing an upgrade from Laravel 4.2 to 5.4, and am making use of the Frozennode Administrator, where it worked quite adequately in 4.2. I'm using:
"exodusanto/administrator" : " 5.4.*",
"frozennode/administrator" : "^5.0",

and have placed the appropriate config files in their respective areas. I'm using the DB facade here (in one of the model configs):

```
'filters' => array(
		'user_id' => array(
			'title' => 'User',
			'type' => 'enum',
			'options' => DB::table('users')->where('confirmed', '=', 1)->orderBy('username', 'asc')->lists('username'),
		),
	),
```
and am receiving the Fatal error in the title. 
Is this a situation where I need to use a Service Provider in some fashion? If so, can you give me an example of how this is done?

**Comment by Bulmer** [comment]
Try using "\DB" instead. It looks like a namespacing problem.

**Comment by jmichaelterenin** [comment]
Hi Bulmer,
Thanks for replying. Yes, I agree, it looks like a namespacing problem, but \DB doesn't work either

**Comment by exodusanto** [comment]
Hi @jmichaelterenin,

I'm pretty sure that you can't use in that way a Closure

```
'id' => array(
            'title' => 'Id',
            'type' => 'enum',
            'options' => function(){
                $arr = DB::table('users')->orderBy('name', 'asc')->select('id')->get()->map(function($b){
                    return "".$b->id;
                })->all();

                return $arr;
            }
        ),

```

Another thing, in laravel 5.4 you can't use anymore ``` ->list() ``` for retrieving a list use can use ``` ->get()->all() ```

**Comment by jmichaelterenin** [comment]
Thank you for the closure suggestion, too many hours on these upgrade fixes, should've known.
Btw, pluck can be used as a substitute for lists.
